### ISSUE TITLE
.: -: no Go files

### ISSUE THREAD

**Issue by priyolahiri** [google/go-licenses#109]
Steps to reproduce:

1. Check out git@github.com:mongodb/mongodb-atlas-kubernetes.git
2. install and run go-licenses csv . from the directory

Output: 
F0225 13:03:44.868040   99714 main.go:43] errors for ["."]:
.: -: no Go files in /pathtorepo

**Comment by wlynch** [comment]
I think this is WAI? There is not a Go package in the top level folder of https://github.com/mongodb/mongodb-atlas-kubernetes

go-licenses expects a package path similar to `go build`. Would `go-licenses csv ./...` work for what you want?

**Comment by Bobgy** [comment]
https://github.com/google/go-licenses/pull/111 added documentation for what package formats are supported
