### ISSUE TITLE
v1.1.0 go modules issue

### ISSUE THREAD

**Issue by leonbergr** [google/go-licenses#126]
I might have some special setup of go modules which does not work with v1.1.0.

Folder structure:
- mainFolder/
    - subFolder1
    - subFolder2
    - subFodler3
    - vendor
    - go.mod
    - go.sum

`vendor` folder is constructed with command `mainFolder/go mod vendor`

`go-licences csv mainFolder/subFolder1 > used_licences.csv` command stopped working.

The thing is, that there is no .mod file in mainFolder/subFolder1, because it is handled in folder above, which includes also `vendor`.

**Comment by leonbergr** [comment]
Your question made me realized that that I am in reality running it in `/mainFolder/backend/scripts/licences` folder and not in `mainFolder`. I switched working directory and now it works fine. Thank you!


ref:
`E0411 13:20:30.547889   16970 library.go:102] Failed to find license for github.com/gin-contrib/sessions/cookie: licenses.Find: rootDir /home/circleci/.go_workspace/src/mainFolder/backend/scripts/licences should contain dir /home/circleci/.go_workspace/src/mainFolder/backend/vendor/github.com/gin-contrib/sessions/cookie`

Diff in generated file:
```
-github.com/gin-contrib/sessions,Unknown,MIT
+github.com/gin-contrib/sessions,Unknown,Unknown
```

**Comment by Bobgy** [comment]
Cool, glad you figured it out!
