### ISSUE TITLE
Add Bazel support

### ISSUE THREAD

**Issue by serafeimgr** [google/go-licenses#134]
Is there a possibility to support Bazel and not only the native Go tooling?

**Comment by Bobgy** [comment]
Does go-licenses 1.0 work with bazel?

**Comment by serafeimgr** [comment]
AFAIU no it does not.

Bazel fetches the depedencies based on rules on the WORKSPACE file and stores them in different directories than the native go tooling

**Comment by Bobgy** [comment]
https://docs.bazel.build/versions/0.24.0/be/functions.html#licenses

Should bazel handle licenses by itself? It already has dependency info for all packages including, but not limited to Go.

**Comment by serafeimgr** [comment]
hey @Bobgy i think this refers to the license of the app not of the depedencies
