### ISSUE TITLE
go-licenses command is not recognized

### ISSUE THREAD

**Issue by ConsciousCoder1** [google/go-licenses#170]
go-license command is not recognized even though go files were moved to /usr/local. 
![Screenshot from 2022-12-06 17-02-24](https://user-images.githubusercontent.com/46510726/206032975-d7ceb011-9262-4b8d-b973-826c8d12a9ea.png)

**Comment by Bobgy** [comment]
You can refer to https://go.dev/doc/tutorial/compile-install
