### ISSUE TITLE
Provide binaries and releases

### ISSUE THREAD

**Issue by gssbzn** [google/go-licenses#21]
Hi, I was wondering if it would be possible to provide proper release versions and binaries along with them?
Today we hit a weird issue on our CI as github.com/otiai10/copy introduced a breaking change on their [latest release](https://github.com/otiai10/copy/releases/tag/v1.2.0) and the way we were installing `go-licenses` was triggering this problem, our CI is a bit weird but so far we managed to solve it with some extra conf but having a binary we can just download and run would solve this kind of issue (not to mention that is also usually faster to do it like that)

So leaving this here for consideration

**Comment by DylanMeeus** [comment]
Running into the same issue here :/

**Comment by gssbzn** [comment]
@DylanMeeus the way we solved this was running `go get` with `GO111MODULE=on`, we just had to go thru some hoops on our ci as running `go get` with  `GO111MODULE=on` in a folder with a `go.mod` file will add the dependency to the file (this is a known "feature" with no way around it so far)  and we did not want that on our ci, hence why I think binaries would help a lot

**Comment by DylanMeeus** [comment]
Thanks @gssbzn, I'll give that a try!
Luckily nothing urgent though as we don't update our external dependencies all that often. Having release tags would help a great deal in preventing these issues :-)

**Comment by RJPercival** [comment]
Would a Docker image suffice? There's already a Dockerfile that should always build, and it should be relatively easy to [release Docker images](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages).

**Comment by gssbzn** [comment]
@RJPercival it would be a start for sure, our ci doesn't have the best docker support but we are working on it.
I also have some experience setting up goreleaser if that's an approach some of the contributors are willing to try I'm happy to make a PR but having something like that means the maintainers are happy to at least tag the release

**Comment by RJPercival** [comment]
They should be; the [v1 milestone](https://github.com/google/go-licenses/milestone/1) is complete so I think it's ready for a v1.0.0 tag.

**Comment by gssbzn** [comment]
with go1.16 I think this can be closed as in theory now there's an option to not alter the the go.mod file, I still need to test this on our CI env as we are still adding 1.16 support

**Comment by Bobgy** [comment]
There are releases now and with go1.16+ `go install github.com/google/go-licenses@latest`, I think these problems are addressed. Please comment if it's still an issue.
