### ISSUE TITLE
Error when 'import' or 'go get'

### ISSUE THREAD

**Issue by zatamine** [google/go-licenses#22]
```
$ go get github.com/google/go-license
/src/github.com/google/go-licenses/save.go:121:22: cannot use func literal (type func(string) bool) as type func(string) (bool, error) in field value
```

**Comment by otiai10** [comment]
Thank you. Fixing it now.

**Comment by otiai10** [comment]
@zatamine Just FYI, this Dockerfile works

```dockerfile
FROM golang:latest
ENV GO111MODULE=on
RUN go get -v github.com/google/go-licenses
```

**Comment by zatamine** [comment]
> @zatamine Just FYI, this Dockerfile works
> 
> ```dockerfile
> FROM golang:latest
> ENV GO111MODULE=on
> RUN go get -v github.com/google/go-licenses
> ```

**Comment by zatamine** [comment]
> @zatamine Just FYI, this Dockerfile works
> 
> ```dockerfile
> FROM golang:latest
> ENV GO111MODULE=on
> RUN go get -v github.com/google/go-licenses
> ```
Thank you for the feedback
I'm using go 1.13 version, the `GO111MODULE` is `auto`, you should add it to the README file, and why you don't tag the branch ? => https://blog.golang.org/publishing-go-modules
