### ISSUE TITLE
Transitive dependencies scan

### ISSUE THREAD

**Issue by ksastan** [google/go-licenses#24]
Hello there!

Didn't find information about possibility to scan transitive dependencies.
For example I have project with several dependencies, this dependencies has their own dependencies, and their dependencies has dependencies ... etc.

Can I get list of all dependencies of dependencies with their licenses?
Or maybe you solve this problem by another way?

**Comment by alb-csms** [comment]
Any update on this?

**Comment by Bobgy** [comment]
I think the tool already detects transitive dependencies for you.
