### ISSUE TITLE
Repository url paths should be versioned

### ISSUE THREAD

**Issue by KnicKnic** [google/go-licenses#33]
Rather than always give a url to master, give to the appropriate tree.

Example in project go-licenses I ran `PS C:\Users\nmaliwa\go\src\github.com\google\go-licenses> .\go-licenses.exe csv .`

we get output 
`github.com/spf13/cobra,https://github.com/spf13/cobra/blob/master/LICENSE.txt,Apache-2.0`
we also know that it is tag v0.0.5
I would expect
`github.com/spf13/cobra,https://github.com/spf13/cobra/blob/v0.0.5/LICENSE.txt,Apache-2.0`

**Comment by dbaumgarten** [comment]
+1 for this. The guys from my legal departement want the license-link for the exact version of every open-source component I use.
If go-licenses would directly provide the correct link, that would be tremendously helpful.

**Comment by Bobgy** [comment]
Fixed in https://github.com/google/go-licenses/pull/94
