### ISSUE TITLE
Support uppercase and lowercase letters and other extensions

### ISSUE THREAD

**Issue by d-tsuji** [google/go-licenses#41]
I'd like to be able to get license files for uppercase and lowercase letters, `.md` and other extensions as well.

For example, I want to target license files that exist in the following repositories.

https://github.com/josharian/intern

While the above repositories are indeed MIT-licensed, they are not covered by go-licenses.

Thank you :)

**Comment by future-tsuji** [comment]
same https://github.com/google/go-licenses/pull/19

**Comment by treuherz** [comment]
I think #19 would solve this, would you mind taking a look at it to confirm?

**Comment by Bobgy** [comment]
cc @wlynch the issue should be closed now

**Comment by d-tsuji** [comment]
Thank you!
