### ISSUE TITLE
Can not detect license of packages imported only in tests

### ISSUE THREAD

**Issue by blanet** [google/go-licenses#62]
`go-licenses` can not detect packages that only imported in tests. Do we have any plan to support it?

**Comment by lwaddicor** [comment]
This functionality would be very useful

**Comment by Bobgy** [comment]
https://github.com/google/go-licenses/blob/d483853b331efc7ed3db237eb30cc12998654fbb/licenses/library.go#L63-L66

If the config here gets a `Tests: true` argument, it also searches for test packages. Welcome making this an optional flag.

**Comment by davidhsingyuchen** [comment]
This will be very helpful.

@blanet It seems that you started some experiments with the change, and I'm wondering if you plan to continue working on it. If not, maybe I can take a look at this and credit your work. Thanks!

**Comment by blanet** [comment]
@davidhsingyuchen Thansk! Just feel free to go on with my old work if they can help!

**Comment by davidhsingyuchen** [comment]
@Bobgy Could you help share when a release will be cut to include this feature? Asking here because `CONTRIBUTING.md` does not seem to mention release process. Thanks!

**Comment by Bobgy** [comment]
Here you go: https://github.com/google/go-licenses/releases/tag/v1.5.0
