### ISSUE TITLE
`go get github.com/google/go-licenses` is broken 

### ISSUE THREAD

**Issue by haiyanmeng** [google/go-licenses#75]
https://github.com/google/go-licenses/commit/24e2421190d883269a17ee98960961d0edbee883 seems to break. Running `go get github.com/google/go-licenses` encounters the following error:

```
go: github.com/google/go-licenses upgrade => v0.0.0-20210727195037-24e2421190d8
/go/pkg/mod/github.com/google/licenseclassifier@v0.0.0-20210722185704-3043a050f148/licenses/embed.go:4:2: package embed is not in GOROOT (/usr/local/go/src/embed)
/go/pkg/mod/github.com/google/licenseclassifier@v0.0.0-20210722185704-3043a050f148/licenses/embed.go:5:2: package io/fs is not in GOROOT (/usr/local/go/src/io/fs)
```

**Comment by michaelokuboyejo** [comment]
It seems to be because of this commit https://github.com/google/go-licenses/commit/24e2421190d883269a17ee98960961d0edbee883

which uses the latest version of google's licenseclassifier which was updated 6 days ago to drop support for go 1.14 and 1.15

https://github.com/google/licenseclassifier/commit/3043a050f148a588e7e0c84dce27579dfe17fd2d

**Comment by Byter09** [comment]
We tried to build a new builder image and ended up with this error:
```
package embed: unrecognized import path "embed": import path does not begin with hostname
package io/fs: unrecognized import path "io/fs": import path does not begin with hostname
```

I am quite unsure what happened there but we'll have to pin our CI to a previous commit it seems.

**Comment by melinath** [comment]
Updating to go 1.16 fixed this for me.

**Comment by StianOvrevage** [comment]
After upgrading to go 1.17 now this works for me:

```
go install github.com/google/go-licenses
$GOPATH/bin/go-licenses
```

**Comment by Bobgy** [comment]
Updated documentation, go >= v1.16 is required for latest version of go-licenses.
