### ISSUE TITLE
Find licenses for k8s.io packages

### ISSUE THREAD

**Issue by melinath** [google/go-licenses#78]
go-licenses is not able to fill the "link for license file" for all go libraries, even if that package's repository is linked on pkg.go.dev and is a supported repository location. For example:

Pkg: [`k8s.io/utils`](https://pkg.go.dev/k8s.io/utils)
License link: https://github.com/kubernetes/utils/blob/master/LICENSE

Currently go-licenses is unable to discover this license link.

**Comment by Bobgy** [comment]
IIUC, the most common reason is:
* you are using go modules
* you do not vendor your dependencies

then you will hit the "Error discovering URL" problem
https://github.com/google/go-licenses#error-discovering-url

**Comment by Bobgy** [comment]
and that's the major reason I raised https://github.com/google/go-licenses/issues/70

**Comment by Bobgy** [comment]
Already implemented in https://github.com/google/go-licenses/pull/94.
Going to be released as v1.1
