### ISSUE TITLE
Should find licenses in files with filename extenstions

### ISSUE THREAD

**Issue by wlbr** [google/go-licenses#85]
The tools does not link licenses that are held in files with extensions, e.g. LICENSE.txt as in https://github.com/uber-go/zap/blob/master/LICENSE.txt

Though it seems to find the license (it lists MIT correctly for ZAP), the link to it is missing in the CSV report.

`go.uber.org/zap,Unknown,MIT`
should be
`go.uber.org/zap, https://github.com/uber-go/zap/blob/master/LICENSE.txt,MIT`

**Comment by Bobgy** [comment]
Can you retry with the latest release？A new feature supported getting the URL from go modules info
