### ISSUE TITLE
Ability to ignore unlicensed packages

### ISSUE THREAD

**Issue by sundowndev** [google/go-licenses#88]
Hi, we currently have azure sdk dependencies that have direct dependencies with internal packages which doesn't contain license. As it's a indirect dependency on our side, we can't just bump to a version that contains a license file, we need to have the ability to avoid checking license of those dependencies. In other terms, we want to avoid having errors for packages on which we don't have any control.

### Examples

```shell
$ go-licenses save . --save_path=./acknowledgements \
  --filter github.com/Azure/azure-sdk-for-go/sdk/internal/log \
  --filter github.com/Azure/azure-sdk-for-go/sdk/internal/diag \
  --filter github.com/Azure/azure-sdk-for-go/sdk/internal/errorinfo \
  --filter github.com/Azure/azure-sdk-for-go/sdk/internal/uuid

$ go-licenses save . --save_path=./acknowledgements --filter github.com/Azure/azure-sdk-for-go/sdk/internal/*

# Another option would be to provide an option to ignore all packages that doesn't contain a license file.
$ go-licenses save . --save_path=./acknowledgements --ignore-unlicensed
# or
$ go-licenses save . --save_path=./acknowledgements --skip-missing
```

**Comment by dschmidt** [comment]
It would be especially nice to be able to exclude the current project.
