### ISSUE TITLE
Rerunning go-licenses now breaks when using --force and already have an output dir

### ISSUE THREAD

**Issue by n3wscott** [google/go-licenses#91]
This PR has introduced a bug where when you run the tool on an existing repo with the output directory in the project being scanned, https://github.com/google/go-licenses/pull/90/files#diff-63d2514e96da76ad8bd5c2460f4ea67c0a6c6ba1055a8890b7ec0c686bcc183fR70 finds all the previous license, which then are not locatable after https://github.com/google/go-licenses/pull/90/files#diff-63d2514e96da76ad8bd5c2460f4ea67c0a6c6ba1055a8890b7ec0c686bcc183fR76 if you use the tool with the the `--force` flag in play.

_Originally posted by @n3wscott in https://github.com/google/go-licenses/issues/90#issuecomment-996282486_

**Comment by wlynch** [comment]
Thanks for filing this! Can you provide a bit more details for how to reproduce this (e.g. args used, expected result, etc)?

My default stance is to roll this change back if it's causing problems, but I need some help reproducing the issue. 🙏

**Comment by n3wscott** [comment]
Howdy! sorry long delay, holidays...

Here is a little script you can run to see what I am seeing:

```shell
pushd $(mktemp -d)

go install github.com/google/go-licenses@master

go mod init example.com/demo

curl https://www.apache.org/licenses/LICENSE-2.0.txt > LICENSE

cat <<EOF > main.go
package main
import (
  . "github.com/hashicorp/golang-lru"
)
func main() {
  New(128)
}
EOF

go mod tidy

go mod vendor

git init

git add .

git commit -m "after vendor"

go-licenses save ./... --save_path="third_party/VENDOR-LICENSE" --force

git add .

git commit -m "after first licesnse save"

go mod vendor

go-licenses save ./... --save_path="third_party/VENDOR-LICENSE" --force
```

**Comment by n3wscott** [comment]
The error I get locally: 

```text
Error: open /var/folders/65/kbdvw9617tx1x8qh8f6md2xw0000gn/T/tmp.yWaWgyJ1/third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE: no such file or directory
Usage:
  licenses save <package> [flags]

Flags:
      --force              Delete the destination directory if it already exists.
  -h, --help               help for save
      --save_path string   Directory into which files should be saved that are required by license terms

Global Flags:
      --alsologtostderr                  log to standard error as well as files
      --confidence_threshold float       Minimum confidence required in order to positively identify a license. (default 0.9)
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

F1229 12:15:02.542070   57909 main.go:43] open /var/folders/65/kbdvw9617tx1x8qh8f6md2xw0000gn/T/tmp.yWaWgyJ1/third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE: no such file or directory
```

**Comment by n3wscott** [comment]
I think this error is the LICENSE file inside third_party has been indexed, but then it was deleted and then attempted to be accessed.

**Comment by benmoss** [comment]
I think this is the core of the problem:

```
❯ go list ./...
example.com/demo
example.com/demo/third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru
example.com/demo/third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru
```

The third_party directory is being considered a package itself. I think a simple solution might be to move [these lines](https://github.com/google/go-licenses/blob/3178385f14075e3bc0f14d78b421296f8208af89/save.go#L75-L79) to the top of the function so that they are deleted before we list all the packages.

**Comment by benmoss** [comment]
If you change the go.mod to be go 1.16 the problem disappears 🤔

**Comment by benmoss** [comment]
I think part of the problem is that the `third_party` dir is getting treated as a package to be licensified:

```
❯ go list ./...
example.com/demo
example.com/demo/third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru
example.com/demo/third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru
```

**Comment by wlynch** [comment]
Approved #99 to roll back this change. Sorry about the trouble!
